GET http://localhost:3001/api/def

###

POST http://localhost:3001/api/newTickets HTTP/1.1
Content-Type: application/json

{
    "category": "administrative",
    "title": "come fare la lasagna prova <SCRIPT scr = 'file.js'> ciao sono luca mi piace tanto il mare",
    "text": "<p>How to include Scripts : <SCRIPT scr='file.js'> </p>"
}
###

GET http://localhost:3001/api/ticket/1

###

GET http://localhost:3001/api/categories

###

GET http://localhost:3001/api/ticket/text/2

###

POST http://localhost:3001/api/newBlock HTTP/1.1
Content-Type: application/json

{
    "ticketId": 55,
    "text": "How are you?"
}
###